package com.atguigu.sparkaliyun.bean

case class DwdQzQuestion(questionid: Int,
                         parentid: Int,
                         questypeid: Int,
                         quesviewtype: Int,
                         content: String,
                         answer: String,
                         analysis: String,
                         limitminute: String,
                         score: Double,
                         splitscore: Double,
                         status: String,
                         optnum: Int,
                         lecture: String,
                         creator: String,
                         createtime: String,
                         modifystatus: String,
                         attanswer: String,
                         questag: String,
                         vanalysisaddr: String,
                         difficulty: String,
                         quesskill: String,
                         vdeoaddr: String,
                         dt: String,
                         dn: String)
