package com.atguigu.sparkaliyun.bean

case class DwdQzPoint(pointid : Int,
                      courseid : Int,
                      pointname : String,
                      pointyear : String,
                      chapter : String,
                      creator : String,
                      createtime : String,
                      status : String,
                      modifystatus : String,
                      excisenum : String,
                      pointlistid : Int,
                      chapterid : Int,
                      sequece : String,
                      pointdescribe : String,
                      pointlevel : String,
                      typelist : String,
                      score : Double,
                      thought : String,
                      remid : String,
                      pointnamelist : String,
                      typelistids : String,
                      pointlist : String,
                      dt : String,
                      dn : String)
